"""updadete code create o more.

Revision ID: 868c807dfacb
Revises: 7b6c2d1e4f90
Create Date: 2026-03-06 16:42:33.494627

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "868c807dfacb"
down_revision: str | Sequence[str] | None = "7b6c2d1e4f90"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("projects_code_key"), "projects", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("projects_code_key"), "projects", ["code"], postgresql_nulls_not_distinct=False
    )
    # ### end Alembic commands ###
