"""add production_number naming_rules path_templates sort_order

Revision ID: c64e1f84daf0
Revises: baa1b24e0ffb
Create Date: 2026-03-21 15:31:10.626729

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c64e1f84daf0"
down_revision: str | Sequence[str] | None = "baa1b24e0ffb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_deliveries_id"), "deliveries", ["id"], unique=False)
    op.create_index(op.f("ix_delivery_items_id"), "delivery_items", ["id"], unique=False)
    op.drop_index(op.f("ix_entity_tags_entity"), table_name="entity_tags")
    op.create_index(op.f("ix_entity_tags_id"), "entity_tags", ["id"], unique=False)
    op.add_column("episodes", sa.Column("production_number", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_episodes_production_number"), "episodes", ["production_number"], unique=False
    )
    op.create_unique_constraint(
        "uq_episode_project_production_number", "episodes", ["project_id", "production_number"]
    )
    op.drop_index(op.f("ix_notes_entity"), table_name="notes")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_user_unread"), table_name="notifications")
    op.create_index(op.f("ix_notifications_id"), "notifications", ["id"], unique=False)
    op.add_column("projects", sa.Column("naming_rules", sa.JSON(), nullable=True))
    op.add_column("projects", sa.Column("path_templates", sa.JSON(), nullable=True))
    op.add_column("sequences", sa.Column("production_number", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_sequences_production_number"), "sequences", ["production_number"], unique=False
    )
    op.create_unique_constraint(
        "uq_sequence_project_episode_production_number",
        "sequences",
        ["project_id", "episode_id", "production_number"],
    )
    op.add_column("shots", sa.Column("sort_order", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_tags_id"), "tags", ["id"], unique=False)
    op.drop_index(op.f("ix_time_logs_user_date"), table_name="time_logs")
    op.create_index(op.f("ix_time_logs_id"), "time_logs", ["id"], unique=False)
    op.drop_index(op.f("ix_versions_status"), table_name="versions")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_versions_status"), "versions", ["status"], unique=False)
    op.drop_index(op.f("ix_time_logs_id"), table_name="time_logs")
    op.create_index(op.f("ix_time_logs_user_date"), "time_logs", ["user_id", "date"], unique=False)
    op.drop_index(op.f("ix_tags_id"), table_name="tags")
    op.drop_column("shots", "sort_order")
    op.drop_constraint("uq_sequence_project_episode_production_number", "sequences", type_="unique")
    op.drop_index(op.f("ix_sequences_production_number"), table_name="sequences")
    op.drop_column("sequences", "production_number")
    op.drop_column("projects", "path_templates")
    op.drop_column("projects", "naming_rules")
    op.drop_index(op.f("ix_notifications_id"), table_name="notifications")
    op.create_index(
        op.f("ix_notifications_user_unread"), "notifications", ["user_id", "is_read"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_created_at"), "notifications", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_notes_entity"), "notes", ["entity_type", "entity_id"], unique=False)
    op.drop_constraint("uq_episode_project_production_number", "episodes", type_="unique")
    op.drop_index(op.f("ix_episodes_production_number"), table_name="episodes")
    op.drop_column("episodes", "production_number")
    op.drop_index(op.f("ix_entity_tags_id"), table_name="entity_tags")
    op.create_index(
        op.f("ix_entity_tags_entity"), "entity_tags", ["entity_type", "entity_id"], unique=False
    )
    op.drop_index(op.f("ix_delivery_items_id"), table_name="delivery_items")
    op.drop_index(op.f("ix_deliveries_id"), table_name="deliveries")
    # ### end Alembic commands ###
